export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const REQUEST_POSTS = "REQUEST_POSTS";
export const FAILURE_POSTS = "REQUEST_POSTS";
export const SORT_SUBREDDIT_BY = "SORT_SUBREDDIT_BY";
export const SUBREDDIT_FETCH_CANCELLATION = "SUBREDDIT_FETCH_CANCELLATION";
export const SUBREDDIT_FETCH_CANCELLATION_SAVE_OR_DISMISS_TODO = "SUBREDDIT_FETCH_CANCELLATION_SAVE_OR_DISMISS_TODO";

export const RECEIVE_SAMPLE_POST = "RECEIVE_SAMPLE_POST";

export const UPDATE_SAVE_FLAG_OF_TODO = "UPDATE_SAVE_FLAG_OF_TODO";
export const ADD_TODO_TO_LIST = "ADD_TODO_TO_LIST";
export const INITILAIZE_SETTING_LIST = "INITILAIZE_SETTING_LIST";
export const SHOW_ACTIVE_SUBREDDIT_MODAL = "SHOW_ACTIVE_SUBREDDIT_MODAL";
export const SIGN_UP_NEW_USER = "SIGN_UP_NEW_USER";
export const LOGIN_USER =  " LOGIN_USER";
export const LOGOUT_USER =  " LOGOUT_USER";
export const DELETE_TODO_FROM_LIST = "DELETE_TODO_FROM_LIST";
export const SET_FETCHING_TO_UPDATED = "SET_FETCHING_TO_UPDATED";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const PERSIST_CATEGORY_LIST = "PERSIST_CATEGORY_LIST";

export const DISPLAY_POSTS_LAYOUT = "DISPLAY_POSTS_LAYOUT";
export const POSTS_PER_PAGE = "POSTS_PER_PAGE";

export const SAVE_BOOKMARK = "SAVE_BOOKMARK";
export const DELETE_BOOKMARK = "DELETE_BOOKMARK";
export const FETCH_BOOKMARKS = "FETCH_BOOKMARKS";