export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const UPDATE_SAVE_FLAG_OF_TODO = "UPDATE_SAVE_FLAG_OF_TODO";
export const ADD_TODO = "ADD_TODO";
export const INITILAIZE_SETTING_LIST = "INITILAIZE_SETTING_LIST";